apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evil-giraf.fullname" . }}
  labels:
    {{- include "evil-giraf.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evil-giraf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evil-giraf.labels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evil-giraf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: postgres:16
          command: ['sh', '-c',
                    'until pg_isready -h {{ .Release.Name }}-postgresql -p 5432 -U {{ .Values.postgresql.auth.username }}; do echo waiting for database; sleep 2; done;']
          env:
            - name: PGPASSWORD
              value: {{ .Values.postgresql.auth.password }}
        - name: ef-migrations
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          command: ['dotnet', 'ef', 'database', 'update', '--project EvilGiraf']
          env:
            - name: POSTGRES__HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES__PORT
              value: "5432"
            - name: POSTGRES__DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES__USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES__PASSWORD
              value: {{ .Values.postgresql.auth.password }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          env:
            - name: ApiKey
              value: {{ .Values.app.auth.apiKey }}
            - name: POSTGRES__HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES__PORT
              value: "5432"
            - name: POSTGRES__DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES__USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES__PASSWORD
              value: {{ .Values.postgresql.auth.password }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.app.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
