apiVersion: v1
kind: Service
metadata:
  name: {{ include "evil-giraf.fullname" . }}
  labels:
    {{- include "evil-giraf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "evil-giraf.selectorLabels" . | nindent 4 }}
