name: Build

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: github-runner-evilgiraf
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Log into registry
        run: echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login ${{ secrets.REGISTRY_URL }} -u '${{ secrets.REGISTRY_USERNAME }}' --password-stdin

      - name: Build Docker image
        run: docker build -t evil-giraf .
        
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true
          
      - name: Echo Build Number
        run: echo ${{ steps.version.outputs.semVer }}

      - name: Tag Docker image
        run: docker tag evil-giraf '${{ secrets.REGISTRY_URL }}/evil-giraf:${{ github.sha }}'

      - name: Tag Docker image with version
        run: docker tag evil-giraf '${{ secrets.REGISTRY_URL }}/evil-giraf:${{ steps.version.outputs.semVer }}'

      - name: Tag main Docker image with 'latest'
        if: github.ref == 'refs/heads/main'
        run: docker tag evil-giraf '${{ secrets.REGISTRY_URL }}/evil-giraf:latest'

      - name: Push Docker image
        run: docker push -a '${{ secrets.REGISTRY_URL }}/evil-giraf'
