name: Tests

on:
  push:
    branches: '**'

jobs:
  tests:
    name: Tests
    runs-on: github-runner-evilgiraf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Run unit tests
        run: dotnet test
