name: Tests

on: [ push ]

jobs:
  tests:
    name: Tests
    runs-on: github-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test
